import { UserProvider } from '@/context/UserContext'
//Importamos el proveedor del contexto
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className = "min-h-screen" >

        <UserProvider>
          {children} 
        </UserProvider>
        {/*Envolvemos el children en el Proveedor, 
        así todas las páginas podran acceder al contexto*/}
        
      </body>
    </html>
  )
}
